### ISSUE TITLE
README中的例子推理失败

### ISSUE THREAD

**Issue by 1MLightyears** [lyogavin/Anima#11]
在按照Readme中的例子尝试推理的时候，根据报错进行了少数修改：
```python3
# base model
model = LlamaForCausalLM.from_pretrained(
        base_model,
        torch_dtype=torch.float16,
        device_map="auto",
        offload_state_dict = True,
        offload_folder='./offload',
    )

# LORA PEFT adapters
adapter_model = "lyogavin/Anima33B"

model = PeftModel.from_pretrained(
        model,
        adapter_model,
        #torch_dtype=torch.float16,
        device_map={"":0},
    )
model.eval()
```
其中在`LlamaForCausalLM`调用过程中，我添加了`offload_folder`参数（根据[huggingface文档](https://huggingface.co/blog/accelerate-large-models#sharding-state-dicts)）；
在`PeftModel`调用过程中，`device_map`需要设为cuda设备（即0）否则会报OOM；
但是即使经过如此修改后仍不能运行：
```
accelerate/utils/modeling.py:154
ValueError: weight is on the meta device, we need a `value` to put in on 0.
```
我想知道是否是`device_map`参数的问题，以及如何调整？
已经搜索过没有类似问题。

我的配置是
- 硬件 7700X/4070Ti/DDR5-32G
- 操作系统 WSL2-Ubuntu22.04
- Python 3.10.10
- torch 2.0.1 with cuda11.8
- transformers 4.31.0.dev0

**Comment by lyogavin** [comment]
有完整的stack吗？

是在哪个步骤exception的？

看起来感觉像是显存不够。

4070Ti显存多大？

**Comment by 1MLightyears** [comment]
4070Ti的显存是12G.
全部输出和完整的stack如下：
```bash
(base) ➜  ~ python testAnima.py

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/lightyears/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/lightyears/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/lightyears/miniconda3/lib/libcudart.so'), PosixPath('/home/lightyears/miniconda3/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/lightyears/miniconda3/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/lightyears/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 7/7 [01:50<00:00, 15.72s/it]
Traceback (most recent call last):
  File "/home/lightyears/testAnima.py", line 22, in <module>
    model = PeftModel.from_pretrained(
  File "/home/lightyears/miniconda3/lib/python3.10/site-packages/peft/peft_model.py", line 203, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/home/lightyears/miniconda3/lib/python3.10/site-packages/peft/peft_model.py", line 500, in load_adapter
    dispatch_model(
  File "/home/lightyears/miniconda3/lib/python3.10/site-packages/accelerate/big_modeling.py", line 373, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/lightyears/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 497, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/lightyears/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
  File "/home/lightyears/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 253, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/home/lightyears/miniconda3/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 154, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: weight is on the meta device, we need a `value` to put in on 0.
```
看起来这个错误是由于在第20行`model =PeftModel.from_pretrained()`的过程中添加了`device_map`导致的
但是如果不添加这个会报OOM

**Comment by lyogavin** [comment]
感觉是accelerate版本的问题。accelerate更新太快了，经常会break一些东西。

roll back到上一个版本试一下？应该可以：https://github.com/huggingface/accelerate/issues/1289#issuecomment-1515494547

**Comment by 1MLightyears** [comment]
好的，不过回滚到哪个版本呢？因为在`requirements.txt`中没有给出`accelerate`的具体版本

**Comment by lyogavin** [comment]
这个应该可以：accelerate @ git+https://github.com/huggingface/accelerate.git@v0.20.3
