### ISSUE TITLE
Running on Mac get traceback error

### ISSUE THREAD

**Issue by gr3enarr0w** [lyogavin/Anima#123]
Just trying to do the test so okay to share my code
```import mlx.core as mx
from airllm import AutoModel

model = AutoModel.from_pretrained("v2ray/Llama-3-70B")

input_text = [
        #'What is the capital of United States?',
        'I like',
    ]

MAX_LENGTH = 128
input_tokens = model.tokenizer(input_text,
    return_tensors="np",
    return_attention_mask=False,
    truncation=True,
    max_length=MAX_LENGTH,
    padding=False)

input_tokens

generation_output = model.generate(
    mx.array(input_tokens['input_ids']),
    max_new_tokens=20,
    use_cache=True,
    return_dict_in_generate=True)

output = model.tokenizer.decode(generation_output.sequences[0])
print(output)```


Traceback
```found_layers:{'model.embed_tokens.': True, 'model.layers.0.': True, 'model.layers.1.': True, 'model.layers.2.': True, 'model.layers.3.': True, 'model.layers.4.': True, 'model.layers.5.': True, 'model.layers.6.': True, 'model.layers.7.': True, 'model.layers.8.': True, 'model.layers.9.': True, 'model.layers.10.': True, 'model.layers.11.': True, 'model.layers.12.': True, 'model.layers.13.': True, 'model.layers.14.': True, 'model.layers.15.': True, 'model.layers.16.': True, 'model.layers.17.': True, 'model.layers.18.': True, 'model.layers.19.': True, 'model.layers.20.': True, 'model.layers.21.': True, 'model.layers.22.': True, 'model.layers.23.': True, 'model.layers.24.': True, 'model.layers.25.': True, 'model.layers.26.': True, 'model.layers.27.': True, 'model.layers.28.': True, 'model.layers.29.': True, 'model.layers.30.': True, 'model.layers.31.': True, 'model.layers.32.': True, 'model.layers.33.': True, 'model.layers.34.': True, 'model.layers.35.': True, 'model.layers.36.': True, 'model.layers.37.': True, 'model.layers.38.': True, 'model.layers.39.': True, 'model.layers.40.': True, 'model.layers.41.': True, 'model.layers.42.': True, 'model.layers.43.': True, 'model.layers.44.': True, 'model.layers.45.': True, 'model.layers.46.': True, 'model.layers.47.': True, 'model.layers.48.': True, 'model.layers.49.': True, 'model.layers.50.': True, 'model.layers.51.': True, 'model.layers.52.': True, 'model.layers.53.': True, 'model.layers.54.': True, 'model.layers.55.': True, 'model.layers.56.': True, 'model.layers.57.': True, 'model.layers.58.': True, 'model.layers.59.': True, 'model.layers.60.': True, 'model.layers.61.': True, 'model.layers.62.': True, 'model.layers.63.': True, 'model.layers.64.': True, 'model.layers.65.': True, 'model.layers.66.': True, 'model.layers.67.': True, 'model.layers.68.': True, 'model.layers.69.': True, 'model.layers.70.': True, 'model.layers.71.': True, 'model.layers.72.': True, 'model.layers.73.': True, 'model.layers.74.': True, 'model.layers.75.': True, 'model.layers.76.': True, 'model.layers.77.': True, 'model.layers.78.': True, 'model.layers.79.': True, 'model.norm.': True, 'lm_head.': True}
saved layers already found in /Users/clarkeverson/.cache/huggingface/hub/models--v2ray--Llama-3-70B/snapshots/c225789c1d83030f465a0e1ba6d69df55e558fab/splitted_model
Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 106454.42it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/Users/clarkeverson/llama_test/pythonProject/llama-play.py", line 21, in <module>
    generation_output = model.generate(
  File "/Users/clarkeverson/llama_test/pythonProject/.venv/lib/python3.9/site-packages/airllm/airllm_llama_mlx.py", line 254, in generate
    for token in self.model_generate(x, temperature=temperature):
  File "/Users/clarkeverson/llama_test/pythonProject/.venv/lib/python3.9/site-packages/airllm/airllm_llama_mlx.py", line 281, in model_generate
    update_weights = ModelPersister.get_model_persister().load_model(self.layer_names_dict['embed'], self.checkpoint_path)
  File "/Users/clarkeverson/llama_test/pythonProject/.venv/lib/python3.9/site-packages/airllm/persist/mlx_model_persister.py", line 113, in load_model
    raise ex
  File "/Users/clarkeverson/llama_test/pythonProject/.venv/lib/python3.9/site-packages/airllm/persist/mlx_model_persister.py", line 96, in load_model
    layer_state_dict = mx.load(to_load_path)
ValueError: [load] Input must be a file-like object opened in binary mode, or string
error: model.embed_tokens, /Users/clarkeverson/.cache/huggingface/hub/models--v2ray--Llama-3-70B/snapshots/c225789c1d83030f465a0e1ba6d69df55e558fab/splitted_model

Process finished with exit code 1```

**Comment by gr3enarr0w** [comment]
was able to fix by adding str( to a line

**Comment by shahfasal** [comment]
@gr3enarr0w which line?

**Comment by sourcedexter** [comment]
I cannot believe they didn't share which line to add the str() to. After a lot of trial and error I have figured it out. 

So, @shahfasal  - you need to add that to themx library file : mx_model_persister.py  . on line 96. 

code before changes: 
`layer_state_dict = mx.load(to_load_path)`

code after changes: 

`layer_state_dict = mx.load(str(to_load_path))`

Please note there might be another place where this change could also be done, but the change above made the code work.
