### ISSUE TITLE
Mistral Model ValueError: Asking to pad but the tokenizer does not have a padding token

### ISSUE THREAD

**Issue by birdup000** [lyogavin/Anima#77]
Hi when I run the newest Mistral model mistralai/Mixtral-8x7B-v0.1 

```python
from airllm import AirLLMMistral

MAX_LENGTH = 128
# could use hugging face model repo id:
model = AirLLMMistral("mistralai/Mixtral-8x7B-v0.1",
                     compression='4bit' # specify '8bit' for 8-bit block-wise quantization 
                    )


# or use model's local path...
#model = AirLLMLlama2("/home/ubuntu/.cache/huggingface/hub/models--garage-bAInd--Platypus2-70B-instruct/snapshots/b585e74bcaae02e52665d9ac6d23f4d0dbc81a0f")

input_text = [
        'how to build a computer?',
        #'I like',
    ]

input_tokens = model.tokenizer(input_text,
    return_tensors="pt", 
    return_attention_mask=False, 
    truncation=True, 
    max_length=MAX_LENGTH, 
    padding=True)
           
generation_output = model.generate(
    input_tokens['input_ids'].cuda(), 
    max_new_tokens=50,
    use_cache=True,
    return_dict_in_generate=True)

output = model.tokenizer.decode(generation_output.sequences[0])

print(output)
```
I get this error

```
Traceback (most recent call last):
  File "/mnt/aedc235c-d458-41cb-88fa-1da70ef3b1bc/AirLLM/myAI.py", line 18, in <module>
    input_tokens = model.tokenizer(input_text,
  File "/home/bird/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2802, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/bird/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2888, in _call_one
    return self.batch_encode_plus(
  File "/home/bird/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3070, in batch_encode_plus
    padding_strategy, truncation_strategy, max_length, kwargs = self._get_padding_truncation_strategies(
  File "/home/bird/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2707, in _get_padding_truncation_strategies
    raise ValueError(
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
```

**Comment by lyogavin** [comment]
you can turn the padding off here:

```python
input_tokens = model.tokenizer(input_text,
    return_tensors="pt", 
    return_attention_mask=False, 
    truncation=True, 
    max_length=MAX_LENGTH, 
    padding=True  #<-----------   set it to False
)
````

**Comment by birdup000** [comment]
> ```python
> False
> ```

Thanks it goes away but now it doesn't work for loading the model correctly. 
```
Traceback (most recent call last):
  File "/mnt/aedc235c-d458-41cb-88fa-1da70ef3b1bc/AirLLM/myAI.py", line 25, in <module>
    generation_output = model.generate(
  File "/home/bird/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/bird/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1718, in generate
    return self.greedy_search(
  File "/home/bird/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2579, in greedy_search
    outputs = self(
  File "/home/bird/.local/lib/python3.10/site-packages/airllm/airllm_mistral.py", line 194, in __call__
    return self.forward(*args, **kwargs)
  File "/home/bird/.local/lib/python3.10/site-packages/airllm/airllm_mistral.py", line 258, in forward
    self.move_layer_to_device(state_dict)
  File "/home/bird/.local/lib/python3.10/site-packages/airllm/airllm_mistral.py", line 147, in move_layer_to_device
    set_module_tensor_to_device(self.model, param_name, self.running_device, value=param,
  File "/home/bird/.local/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 293, in set_module_tensor_to_device
    value = value.to(dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacty of 5.78 GiB of which 146.38 MiB is free. Including non-PyTorch memory, this process has 4.88 GiB memory in use. Of the allocated memory 4.63 GiB is allocated by PyTorch, and 167.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by birdup000** [comment]
@lyogavin
